[pytest]
testpaths = backend
python_files = test_*.py
addopts = -s
filterwarnings =
    error
    ignore::DeprecationWarning:shap.*:
    ignore::PendingDeprecationWarning:shap.*:
    ignore::DeprecationWarning:pydantic.*:
    ignore::UserWarning:pydantic.*:
    ignore::UserWarning:sklearn.*:
    ignore::FutureWarning:sklearn.*:
    ignore::DeprecationWarning:reportlab.*:
    ignore::DeprecationWarning:pkg_resources.*:
    ignore::DeprecationWarning:google.*:
    ignore::DeprecationWarning:matplotlib.*:
    ignore::PendingDeprecationWarning:matplotlib.*:
    ignore:The set_bad function will be deprecated.*:
    ignore::starlette.exceptions.StarletteDeprecationWarning
    ignore::DeprecationWarning:starlette.*:
