"""
Clinical Copilot Schemas
Pydantic data contracts for:
- Unified Patient Intelligence Dossier
- 7-Part Clinical Assessment
- EMR-ready SOAP Note Synthesizer
- Differential Diagnostic Reasoning
- Clinician Review & Decision Audit Trail
- Severity-Gated Follow-Up Scheduling
"""

from typing import Dict, List, Optional, Any
from pydantic import BaseModel, Field
from datetime import datetime
import uuid


# ==========================================
# 1. Unified Patient Intelligence Dossier
# ==========================================

class PatientDemographics(BaseModel):
    patient_id: str
    full_name: str
    age: int
    gender: str
    bmi: float
    dietary_pattern: str
    meals_per_day: int
    activity_level: str
    sunlight_exposure_min: int
    sleep_hours: float
    stress_level: int
    smoking_status: str
    alcohol_consumption: str


class DeficiencyItem(BaseModel):
    nutrient: str
    risk_level: str  # "LOW", "MODERATE", "HIGH", "CRITICAL"
    probability: float
    percentile: float
    confidence_score: float
    primary_symptom_matches: List[str] = Field(default_factory=list)


class BiomarkerItem(BaseModel):
    marker_name: str
    value: float
    unit: str
    reference_range: str
    status: str  # "LOW", "OPTIMAL", "HIGH", "BORDERLINE"


class SymptomItem(BaseModel):
    symptom: str
    severity: int  # 1 - 10
    duration_weeks: Optional[int] = None
    affected_systems: List[str] = Field(default_factory=list)


class OutcomeTrajectory(BaseModel):
    baseline_health_score: float
    current_health_score: float
    adherence_percentage: float
    projected_recovery_weeks: int
    trajectory_status: str  # "IMPROVING", "STABLE", "DECLINING"


class PrecisionIntervention(BaseModel):
    category: str  # "FOOD", "SUPPLEMENT", "LIFESTYLE"
    title: str
    dosage_or_serving: str
    frequency: str
    biochemical_mechanism: str
    safety_notes: Optional[str] = None


class UnifiedPatientDossier(BaseModel):
    """
    Comprehensive aggregated patient intelligence combining:
    1. Demographics & lifestyle
    2. Model deficiency predictions
    3. Laboratory biomarkers
    4. Clinical symptoms
    5. Longitudinal outcome trajectory
    6. Precision meal & food recommendations
    7. Supplement protocol
    8. Multi-nutrient risk scores
    9. SHAP explainability insights
    10. Safety governance & UL checks
    """
    dossier_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    generated_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    demographics: PatientDemographics
    deficiencies: List[DeficiencyItem]
    biomarkers: List[BiomarkerItem]
    symptoms: List[SymptomItem]
    outcomes: OutcomeTrajectory
    precision_foods: List[PrecisionIntervention]
    supplement_plan: List[PrecisionIntervention]
    composite_risk_score: float
    top_shap_features: List[Dict[str, Any]]
    safety_governance_alerts: List[str]


# ==========================================
# 2. Clinical Assessment Generator
# ==========================================

class ClinicalAssessmentReport(BaseModel):
    """
    Comprehensive 7-part clinical assessment generated by the Clinical Copilot:
    1. Executive Summary
    2. Clinical Findings
    3. Deficiency Risk Summary
    4. Contributing Factors (dietary gaps, absorption inhibitors, genetics)
    5. Recommended Actions (prioritized by urgency)
    6. Monitoring Plan (concrete lab targets)
    7. Follow-Up Recommendations
    """
    assessment_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    patient_id: str
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    executive_summary: str
    clinical_findings: List[str]
    deficiency_risk_summary: Dict[str, Any]
    contributing_factors: List[Dict[str, str]]
    recommended_actions: List[Dict[str, str]]
    monitoring_plan: Dict[str, Any]
    follow_up_recommendations: List[str]
    is_signed_off: bool = False
    reviewer_notes: Optional[str] = None


# ==========================================
# 3. SOAP Note Generator
# ==========================================

class SOAPNoteResponse(BaseModel):
    """
    EMR/EHR-ready SOAP Note with 1-click clipboard formatting for Epic/Cerner.
    """
    note_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    patient_id: str
    patient_name: str
    created_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    subjective: Dict[str, Any]
    objective: Dict[str, Any]
    assessment: Dict[str, Any]
    plan: Dict[str, Any]
    formatted_text: str  # Markdown / EMR copy-paste text


# ==========================================
# 4. Differential Diagnostic Reasoning Engine
# ==========================================

class CompetingCause(BaseModel):
    etiology: str
    likelihood: str  # "HIGH", "MODERATE", "LOW"
    clinical_rationale: str
    distinguishing_features: str


class DifferentialReasoningItem(BaseModel):
    nutrient: str
    predicted_probability: float
    confidence_score: float
    uncertainty_interval: List[float]  # [lower_bound, upper_bound] 95% CI
    primary_suspected_cause: str
    competing_causes: List[CompetingCause]
    confirmatory_diagnostics: List[Dict[str, str]]  # lab test, clinical purpose, target cutoff
    clinical_uncertainty_explanation: str


class DifferentialDiagnosticReport(BaseModel):
    report_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    patient_id: str
    generated_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    differential_items: List[DifferentialReasoningItem]
    diagnostic_algorithm_notes: str


# ==========================================
# 5. Clinician Review Workflow
# ==========================================

class ClinicianReviewRequest(BaseModel):
    patient_id: str
    clinician_id: str
    clinician_name: str
    clinician_role: str = "ATTENDING_PHYSICIAN"
    decision: str  # "APPROVE", "REJECT", "MODIFY", "ESCALATE"
    target_intervention_id: Optional[str] = None
    target_category: str = "OVERALL_CARE_PLAN"
    modifications: Optional[Dict[str, Any]] = None
    rationale: str
    escalation_specialty: Optional[str] = None  # "HEMATOLOGY", "ENDOCRINOLOGY", "GASTROENTEROLOGY"


class ClinicianReviewRecord(BaseModel):
    review_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    timestamp: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    patient_id: str
    clinician_id: str
    clinician_name: str
    clinician_role: str
    decision: str
    target_intervention_id: Optional[str] = None
    target_category: str
    modifications: Optional[Dict[str, Any]] = None
    rationale: str
    escalation_specialty: Optional[str] = None
    audit_hash: str  # SHA-256 tamper-evident hash of review contents


# ==========================================
# 6. Follow-Up Scheduling Engine
# ==========================================

class FollowUpMilestone(BaseModel):
    milestone_days: int  # 30, 60, 90
    target_date: str
    severity_tier: str  # "CRITICAL", "HIGH", "MODERATE", "ROUTINE"
    clinical_objective: str
    labs_to_retest: List[str]
    symptom_checkpoints: List[str]
    escalation_triggers: List[str]


class FollowUpSchedulePlan(BaseModel):
    schedule_id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    patient_id: str
    generated_at: str = Field(default_factory=lambda: datetime.utcnow().isoformat())
    highest_severity: str
    milestones: List[FollowUpMilestone]
    summary_directive: str
