apiVersion: v1
kind: Secret
metadata:
  name: nutriscan-secrets
  namespace: nutriscan-clinical
  labels:
    app.kubernetes.io/name: nutriscan-ai
type: Opaque
stringData:
  DATABASE_URL: "postgresql+asyncpg://nutriscan_prod_usr:k8s_vault_sec_db_2026!@postgres-ha.nutriscan-clinical.svc.cluster.local:5432/nutriscan_clinical"
  JWT_SECRET: "c3VwZXJfc2VjcmV0X2VudGVycHJpc2Vfa2V5XzIwMjZfcGhhc2UxNA=="
